package com.goev.partner.enums.partner;

public enum PartnerStatus {
    LOGGED_IN,PENDING_VERIFICATION,CHECKED_IN,VEHICLE_ASSIGNED,CHECKLIST_PENDING,WAITING_FOR_CHECKLIST_APPROVAL,WAITING_FOR_ONLINE,ONLINE,
    ASSIGNED,ENROUTE,ARRIVED,STARTED,ENDED
}
