package com.goev.partner.enums.partner;

public enum PartnerSubStatus {
    DOCUMENTS_PENDING, DOCUMENTS_UPLOADED,
    NO_DUTY,DUTY_ASSIGNED,
    VEHICLE_NOT_ALLOTTED, VEHICLE_ALLOTTED,

    CHECKLIST_PENDING,WAITING_FOR_CHECKLIST_APPROVAL,CHECKLIST_REJECTED,
    WAITING_FOR_ONLINE,
    RETURN_CHECKLIST_PENDING,WAITING_FOR_RETURN_CHECKLIST_APPROVAL,RETURN_CHECKLIST_REJECTED,

    SOC_ENTRY,ODOMETER_ENTRY, PAUSE,
    NO_BOOKING,ASSIGNED,ENROUTE,ARRIVED,STARTED,ENDED
}
