package com.goev.partner.enums.partner;

public enum PartnerSubStatus {
    DOCUMENTS_PENDING, DOCUMENTS_UPLOADED,
    NO_DUTY,DUTY_ASSIGNED,
    VEHICLE_NOT_ALLOTTED, VEHICLE_ALLOTTED,

    CHECKLIST_PENDING,WAITING_FOR_CHECKLIST_APPROVAL,CHECKLIST_REJECTED,


    SOC_ENTRY,ODOMETER_ENTRY, PAUSE,
    ASSIGNED,ENROUTE,ARRIVED,STARTED,ENDED
}
